name: Publish to gh-pages branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: clone-path

      - name: Install dependencies and run build
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install obsidianhtml
          mkdir clone-path/.obsidian # this folder needs to exist so obsidianhtml can find the root of the vault
          obsidianhtml convert -i clone-path/.publish/config.yml -v
          touch output/html/.nojekyll

      - name: Publish to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: output/html # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
